### ISSUE TITLE
Give user feedback when a video download starts

### ISSUE THREAD

**Issue by CallumMackenzie** [hairyprogrammer/MotisHarmony#3]
Currently, no indication is given that a video has started downloading; it would be better to give the user feedback that a download has started so they do not try to download the video repeatedly.

This does not necessarily need to be visual feedback for video downloading, but rather could just be an indication that the application is doing something at least.

**Comment by CallumMackenzie** [comment]
@Jake-Yeo any updates?

**Comment by Jake-Yeo** [comment]
@CallumMackenzie 
![image](https://user-images.githubusercontent.com/80185436/168193041-b2514e80-d299-488c-aa03-05113ecf3c07.png)
![image](https://user-images.githubusercontent.com/80185436/168193076-c271d9fc-c221-4589-966a-d8bb9f06925b.png)
![image](https://user-images.githubusercontent.com/80185436/168193686-14de9b7d-5cd9-43c2-b33f-c1cf747ecb98.png)

**Comment by Jake-Yeo** [comment]
@CallumMackenzie  Done!
